# Request a Mode change from a PackML State Machine.
# The response is returned as soon as the request is accepted, but not necessarily
# when the mode changes

Mode mode

---
# State Machine response
bool success    # True if Mode has been accepted
int8 error_code # Error code if Mode has been rejected
string message  # Message for display (only for human reading)

# Error Codes
int8 SUCCESS = 1
int8 INVALID_MODE_REQUEST = -1
